export function namespace (): string {
  return `/**
 * File name: {{ namespace }}
 *
 * Generated by moleculejs, please DO NOT modify this file manually.
 */
import { Entity, OptionEntity } from './abstracts'
{{#each imports}}
import { {{#each types}} {{this}}, {{/each}} } from './{{name}}'
{{/each}}

const uint32Length = {{size-of 'MOL_NUM'}}

{{#each declarations}}
  {{#if (is-nil imported_depth)}}
  {{#switch 'type'}}
    {{#case 'array'}} {{>array this}} {{/case}}
    {{#case 'struct'}} {{>struct this}} {{/case}}
    {{#case 'fixvec'}} {{>vector this}} {{/case}}
    {{#case 'dynvec'}} {{>vector this}} {{/case}}
    {{#case 'option'}} {{>option this}} {{/case}}
    {{#case 'table'}} {{>table this}} {{/case}}
  {{/switch}}
  {{/if}}
{{/each}}`
}
